#ifndef _CTP_HTTP_CONSTS_H_
#define _CTP_HTTP_CONSTS_H_

#define CTP_KEY_HEADER_MAX_SIZE   1024
#define CTP_VALUE_HEADER_MAX_SIZE 1024
#define CTP_HEADER_MAX_HEADERS    128

#define CTP_HTTP_METHOD_UNKNOWN 0
#define CTP_HTTP_METHOD_GET     1
#define CTP_HTTP_METHOD_HEAD    2
#define CTP_HTTP_METHOD_POST    3
#define CTP_HTTP_METHOD_PUT     4
#define CTP_HTTP_METHOD_PATCH   5
#define CTP_HTTP_METHOD_DELETE  6
#define CTP_HTTP_METHOD_OPTIONS 7

#define CTP_HTTP_PROTOCOL_UNDEFINED 0
#define CTP_HTTP_PROTOCOL_HTTP_1_1  1
#define CTP_HTTP_PROTOCOL_HTTP_2    2

#define CTP_HTTP_STATUS_OK                         200
#define CTP_HTTP_STATUS_CREATED                    201
#define CTP_HTTP_STATUS_NO_CONTENT                 204

#define CTP_HTTP_STATUS_MOVED_PERMANENTLY          301
#define CTP_HTTP_STATUS_TEMPORARY_REDIRECT         307
#define CTP_HTTP_STATUS_PERMANENT_REDIRECT         308

#define CTP_HTTP_STATUS_BAD_REQUEST                400
#define CTP_HTTP_STATUS_UNAUTHORIZED               401
#define CTP_HTTP_STATUS_FORBIDDEN                  403
#define CTP_HTTP_STATUS_NOT_FOUND                  404

#define CTP_HTTP_STATUS_INTERNAL_SERVER_ERROR      500
#define CTP_HTTP_STATUS_NOT_IMPLEMENTED            501
#define CTP_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED 505

#endif

