#ifndef _HTC_HTTP_CONSTS_H_
#define _HTC_HTTP_CONSTS_H_

#define HTC_KEY_HEADER_MAX_SIZE   1024
#define HTC_VALUE_HEADER_MAX_SIZE 1024
#define HTC_HEADER_MAX_HEADERS    128

#define HTC_HTTP_METHOD_UNKNOWN 0
#define HTC_HTTP_METHOD_GET     1
#define HTC_HTTP_METHOD_HEAD    2
#define HTC_HTTP_METHOD_POST    3
#define HTC_HTTP_METHOD_PUT     4
#define HTC_HTTP_METHOD_PATCH   5
#define HTC_HTTP_METHOD_DELETE  6
#define HTC_HTTP_METHOD_OPTIONS 7

#define HTC_HTTP_PROTOCOL_UNDEFINED 0
#define HTC_HTTP_PROTOCOL_HTTP_1_1  1
#define HTC_HTTP_PROTOCOL_HTTP_2    2 // NOT IMPLEMENTED

#define HTC_HTTP_STATUS_OK                         200
#define HTC_HTTP_STATUS_CREATED                    201
#define HTC_HTTP_STATUS_NO_CONTENT                 204

#define HTC_HTTP_STATUS_MOVED_PERMANENTLY          301
#define HTC_HTTP_STATUS_TEMPORARY_REDIRECT         307
#define HTC_HTTP_STATUS_PERMANENT_REDIRECT         308

#define HTC_HTTP_STATUS_BAD_REQUEST                400
#define HTC_HTTP_STATUS_UNAUTHORIZED               401
#define HTC_HTTP_STATUS_FORBIDDEN                  403
#define HTC_HTTP_STATUS_NOT_FOUND                  404

#define HTC_HTTP_STATUS_INTERNAL_SERVER_ERROR      500
#define HTC_HTTP_STATUS_NOT_IMPLEMENTED            501
#define HTC_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED 505

#endif

